name: table
description: >
  Display tabular data with ease. Perform paging, sorting and filtering without extra code.
version: 0.0.1-dev
repository: https://github.com/PlugFox/table
issue_tracker: https://github.com/PlugFox/table/issues
homepage: https://github.com/PlugFox/table
#publish_to: https://pub.dev
#documentation: https://pub.dev/documentation/table/latest/
#authors:
#  - Plague Fox <plugfox@gmail.com>

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  test: ^1.20.2
  mockito: ^5.1.0
  grinder: ^0.9.1
